-- 코드를 입력하세요
-- 판매날짜, 상품ID, 유저ID, 판매량
# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE, 
# PRODUCT_ID, USER_ID, SALES_AMOUNT
# FROM ONLINE_SALE
# WHERE SUBSTR(SALES_DATE,1,7)="2022-03"

# UNION

# SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE, 
# PRODUCT_ID, Null as USER_ID,  SALES_AMOUNT
# FROM OFFLINE_SALE
# WHERE SUBSTR(SALES_DATE,1,7)="2022-03"

(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE AS F
WHERE SALES_DATE LIKE '2022-03%')
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID


 