WITH CTE AS (
    SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR AS A JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE IN ('세단', 'SUV') AND A.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
)
SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * ((100-B.DISCOUNT_RATE)/100) * 30, 0) AS FEE
FROM CTE AS A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B ON A.CAR_TYPE = B.CAR_TYPE
WHERE B.DURATION_TYPE = '30일 이상' AND ROUND(A.DAILY_FEE * ((100-B.DISCOUNT_RATE)/100) * 30, 0) BETWEEN 500000 AND 2000000