-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, 
ROUND(((A.DAILY_FEE - ((A.DAILY_FEE * (C.DISCOUNT_RATE*0.01)))) * 30) ,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV') AND 
C.DURATION_TYPE = '30일 이상' AND
A.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
) AND 
(((A.DAILY_FEE - ((A.DAILY_FEE * (C.DISCOUNT_RATE*0.01)))) * 30) 
     BETWEEN 500000 AND 1999999)
ORDER BY 3 DESC, 2, 1 DESC