SELECT ID,
CASE
    WHEN rr=1 THEN 'CRITICAL'
    WHEN rr=2 THEN 'HIGH'
    WHEN rr=3 THEN 'MEDIUM'
    WHEN rr=4 THEN 'LOW'
END AS 'COLONY_NAME'
FROM (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS 'rr' 
    FROM ECOLI_DATA
) AS tmp
ORDER BY ID ASC