WITH CTE AS (
    SELECT COUNT(*) AS TOTAL FROM USER_INFO WHERE YEAR(JOINED) = 2021
), CTE_2 AS (
    SELECT DISTINCT A.USER_ID, B.SALES_DATE FROM USER_INFO AS A JOIN ONLINE_SALE AS B ON A.USER_ID = B.USER_ID WHERE YEAR(A.JOINED) = 2021
)

SELECT 
YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT USER_ID) / (SELECT TOTAL FROM CTE) ,1) AS PUCHASED_RATIO
FROM CTE_2
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2

