WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT a.ID, a.PARENT_ID, b.GENERATION + 1
    FROM ECOLI_DATA AS a
    INNER JOIN CTE AS b
    ON a.PARENT_ID = b.ID
),
CTE_A AS (
    SELECT * 
    FROM CTE 
    WHERE ID IN (
        SELECT ID FROM ECOLI_DATA WHERE ID NOT IN (
            SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
        )
    )
)

SELECT COUNT(*) AS COUNT, GENERATION FROM CTE_A
GROUP BY GENERATION
ORDER BY 2 ASC

# WITH 
# SELECT COUNT(*) AS COUNT, GENERATION 
# FROM CTE 
# GROUP BY GENERATION
# HAVING ID IN (
#     SELECT ID FROM ECOLI_DATA WHERE ID NOT IN (
#         SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
#     )
# )
# ORDER BY 2 ASC