WITH CTE AS (
    SELECT ID, PARENT_ID, SIZE_OF_COLONY,
        CASE 
            WHEN MONTH(DIFFERENTIATION_DATE)<=3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE)>=4 AND MONTH(DIFFERENTIATION_DATE)<=6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE)>=7 AND MONTH(DIFFERENTIATION_DATE)<=9 THEN '3Q'
            ELSE '4Q'
        END AS 'QUARTER'
    FROM ECOLI_DATA
)

SELECT QUARTER, COUNT(*) ECOLI_COUNT FROM CTE GROUP BY QUARTER
ORDER BY 1

# SELECT CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q')  AS QUARTER, 
# COUNT(*) AS ECOLI_COUNT
# FROM ECOLI_DATA GROUP BY CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q')
# ORDER BY 1