SELECT B.HISTORY_ID, 
CASE
WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7 AND DATEDIFF(B.END_DATE, B.START_DATE) + 1 < 30 THEN ROUND(A.DAILY_FEE * ((100 - (
    SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상' AND CAR_TYPE = '트럭'
    ))/100) * (DATEDIFF(B.END_DATE, B.START_DATE) + 1),0)
    
WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30 AND DATEDIFF(B.END_DATE, B.START_DATE) + 1 < 90 THEN ROUND(A.DAILY_FEE * ((100 - (
    SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상' AND CAR_TYPE = '트럭'
    ))/100) * (DATEDIFF(B.END_DATE, B.START_DATE) + 1), 0)

WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90 THEN ROUND(A.DAILY_FEE * ((100 - (
    SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상' AND CAR_TYPE = '트럭'
    ))/100) * (DATEDIFF(B.END_DATE, B.START_DATE) + 1), 0)

ELSE ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE) + 1), 0)
END AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC