-- 코드를 입력하세요
WITH tmp AS (
    SELECT CAR_TYPE, DURATION_TYPE, SUBSTRING(DISCOUNT_RATE, 1, 2) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT
B.HISTORY_ID, 

CASE 
    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 7 THEN ROUND(A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE)+1), 0)

    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 7 AND DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30 THEN ROUND(A.DAILY_FEE*(0.01 * (100-t7.DISCOUNT_RATE)) * (DATEDIFF(B.END_DATE, B.START_DATE)+1), 0)

    WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 30 AND DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 THEN ROUND(A.DAILY_FEE*(0.01 * (100-t30.DISCOUNT_RATE)) * (DATEDIFF(B.END_DATE, B.START_DATE)+1), 0)

    ELSE ROUND(A.DAILY_FEE*(0.01 * (100-t90.DISCOUNT_RATE)) * (DATEDIFF(B.END_DATE, B.START_DATE)+1), 0)
    
END AS 'FEE'

FROM CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B 
ON A.CAR_ID = B.CAR_ID 
JOIN tmp AS t7 ON t7.DURATION_TYPE = '7일 이상'
JOIN tmp AS t30 ON t30.DURATION_TYPE = '30일 이상'
JOIN tmp AS t90 ON t90.DURATION_TYPE = '90일 이상'
WHERE A.CAR_TYPE = '트럭' 
ORDER BY 2 DESC, 1 DESC
