WITH CTE AS (
SELECT A.FLAVOR, A.Q + B.W AS QQ FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS Q FROM FIRST_HALF GROUP BY FLAVOR) AS A JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS W FROM JULY GROUP BY FLAVOR) AS B ON A.FLAVOR = B.FLAVOR
)
SELECT FLAVOR FROM CTE ORDER BY QQ DESC LIMIT 3