# SELECT * FROM ANIMAL_OUTS
WITH RECURSIVE TMP (n) AS (
    SELECT 0
    UNION ALL
    SELECT n+1 FROM TMP WHERE n < 23
)


SELECT 
A.n AS HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM TMP AS A LEFT JOIN ANIMAL_OUTS AS B ON A.n = HOUR(B.DATETIME)
GROUP BY A.n
ORDER BY 1