WITH RECURSIVE CTE AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n+1 FROM CTE WHERE n<23
)

SELECT A.n, COUNT(B.ANIMAL_ID) AS COUNT FROM CTE AS A LEFT JOIN ANIMAL_OUTS AS B ON A.n = HOUR(B.DATETIME)
GROUP BY A.n
ORDER BY 1