WITH CTE AS (
    SELECT A.EMP_NO, A.EMP_NAME, AVG(B.SCORE) AS 'avg', A.SAL
    FROM HR_EMPLOYEES AS A JOIN HR_GRADE AS B ON A.EMP_NO = B.EMP_NO
    GROUP BY A.EMP_NO
),
CTE_2 AS (
    SELECT EMP_NO, EMP_NAME,
    (CASE 
    WHEN avg >= 96 THEN 'S'
    WHEN avg >= 90 THEN 'A'
    WHEN avg >= 80 THEN 'B'
    ELSE 'C'
    END) AS GRADE, SAL FROM CTE 
)

SELECT EMP_NO, EMP_NAME, GRADE, 
(CASE 
    WHEN GRADE = 'S' THEN SAL * 0.2
    WHEN GRADE = 'A' THEN SAL * 0.15
    WHEN GRADE = 'B' THEN SAL * 0.1
    ELSE 0
END) AS 'BONUS'
FROM CTE_2
ORDER BY 1