SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE 
FROM MEMBER_PROFILE AS A JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN (
    /*가장 많은 리뷰를 쓴 사람의 ID */
    SELECT A.MEMBER_ID FROM MEMBER_PROFILE AS A JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY A.MEMBER_ID
    HAVING COUNT(*) = (
        /*가장 많은 리뷰 개수*/
        SELECT COUNT(*) AS CNT 
        FROM MEMBER_PROFILE AS A JOIN REST_REVIEW AS B ON A.MEMBER_ID = B.MEMBER_ID
        GROUP BY A.MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    )
)
ORDER BY REVIEW_DATE, B.REVIEW_TEXT