-- 코드를 작성해주세요
-- 모두 가지고 있으려면 내 형질이랑 부모 형질 & 해서 1인거는 아닌데
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA as A
INNER JOIN ECOLI_DATA as B
ON B.ID = A.PARENT_ID
WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY ID ASC