WITH TMP AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE 
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID 
FROM ECOLI_DATA AS A JOIN TMP AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1, 2