WITH TEMP AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE
)

SELECT A.ID, C.FISH_NAME, A.LENGTH FROM FISH_INFO AS A INNER JOIN TEMP AS B ON A.FISH_TYPE = B.FISH_TYPE INNER JOIN FISH_NAME_INFO AS C ON A.FISH_TYPE = C.FISH_TYPE 
WHERE A.LENGTH = B.LENGTH
ORDER BY 1 ASC