WITH CTE AS (
    SELECT 'Front_End' AS NAME, SUM(CODE) AS 'CODE' FROM SKILLCODES WHERE CATEGORY = 'Front End'
    UNION ALL
    SELECT NAME, CODE FROM SKILLCODES WHERE NAME in ('Python', 'C#')
)

SELECT * FROM (
SELECT 
(CASE
WHEN SKILL_CODE & (SELECT CODE FROM CTE WHERE NAME = 'Front_End') AND SKILL_CODE & (SELECT CODE FROM CTE WHERE NAME = 'Python') THEN 'A'
WHEN SKILL_CODE & (SELECT CODE FROM CTE WHERE NAME = 'C#') THEN 'B'
WHEN SKILL_CODE & (SELECT CODE FROM CTE WHERE NAME = 'Front_End') THEN 'C'
ELSE 'None'
END) AS GRADE, ID, EMAIL
FROM DEVELOPERS) AS sub WHERE GRADE != 'None' ORDER BY 1, 2